-- Heartbeat log for the nightly mandarin-pipeline refresh (daily_refresh.py).
-- One row per run: written "running" at start, then updated to "ok" /
-- "issues" / "crashed" at the end. A separate Vercel cron watchdog
-- (/api/pipeline-watchdog) checks the most recent row to detect a run that
-- never started at all (e.g. the Mac was off/asleep) or one that started
-- but never finished (crash/hang) — the local script can't report either
-- of those on its own, since it's the very thing that failed to run.

create table if not exists pipeline_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'running', -- running | ok | issues | crashed
  summary text
);

create index if not exists pipeline_runs_started_at_idx on pipeline_runs (started_at desc);

grant select, insert, update on pipeline_runs to service_role;
